### ISSUE TITLE
PPTV聚体育被强制升级到2.1.0后不能看

### ISSUE THREAD

**Issue by phillipouyang** [yanggis/ChinaTunnel#38]
已安装Chinatunnel 1.7.6,  之前PPTV聚体育2.0.4 能看，但被强制升级到2.1.0后不能看 （已更新白名单）
报错：
服务器返回非法数据
错误码：1_2_00D1200

海美迪H7三代盒子   (已root)
位置：加拿大

非常感谢！！！

**Comment by yanggis** [comment]
谢谢反馈，这个问题我要测试一下，最近非常忙，估计要四五天才能处理这个事情。

**Comment by phillipouyang** [comment]
谢谢!

**Comment by sorrych** [comment]
海外有部分地区芒果可正常观看，但是魔力视频腾讯等突然提示无法观看，一直在加载中

**Comment by yanggis** [comment]
腾讯视频请用腾讯云视听观看
芒果TV哪个视频看不了，能和我说一下嘛？

**Comment by sorrych** [comment]
芒果可以看的，就是有朋友说魔力视频和云视听突然出现无法加载的状况，界面都很难显示出来。但是很奇怪芒果确可以看

**Comment by yanggis** [comment]
哦，能现在再试试看看腾讯视频云视听可以看吗?

**Comment by sorrych** [comment]
明天我再问一下朋友，他那边现在是晚上。如果不行的话就给您回复，谢谢

**Comment by yanggis** [comment]
好的，谢谢。

**Comment by yanggis** [comment]
您好，现在能测试一下腾讯云视听可以看了嘛？

**Comment by phillipouyang** [comment]
pptv聚体育有进展吗？谢！

**Comment by yanggis** [comment]
@phillipouyang 这个我在测试，应该今天或者明天就可以搞定。

**Comment by phillipouyang** [comment]
非常感谢！！！

**Comment by sorrych** [comment]
刚刚试过，pptv聚体育2.02版本可正常观看，2.10版本无法播放，报错：
服务器返回非法数据。辛苦开发者了

**Comment by yanggis** [comment]
@phillipouyang  @sorrych 您好，再试一下看看PPTV可以看了没有？

**Comment by sorrych** [comment]
@yanggis 已测试最新版本，正常了。辛苦了

**Comment by xhaung** [comment]
@yanggis 你好，我也是2.1.0强制更新之后出现“服务器返回数据非法，错误码：-1_2_00D1200"
更新最新版本之后问题并未修复，几乎所有的视频和直播都有一样的问题。

我老爸之前看球基本只靠这个app，也买了会员，现在看球非常困难，希望问题能够修复。多谢

ref: 小米盒子，CIBN聚体育，英国

**Comment by phillipouyang** [comment]
这个已经修复了,  进盒子设置, 清PPTV聚体育数据,  还有在Chintunnel 更新一下白名单,应该能看

**Comment by 442111322** [comment]
你好  我是小米盒子  與樓主問題一樣 （之前PPTV聚体育2.0.4 能看，但被强制升级到2.1.0后不能看 ）
現在是2.12了吧
請問：什麼是Chintunnel    我只看見小米盒子裡面有一個黑名單。
麻煩告訴我應該怎麼弄？我在台灣
謝謝！

**Comment by yuanchongfu** [comment]
C:\Users\Administrator>you-get --format=3 http://v.pptv.com/show/HFozsRlic7y2QDnY.html?rcc_src=L1
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
site:                PPTV
title:               东风破(第01集)
stream:
    - format:        3
      container:     mp4
      video-profile: 1920x1080@2573kbps
      size:          836.2 MiB (876772936 bytes)
    # download-with: you-get --format=3 [URL]

Downloading 东风破(第01集).mp4 ...
 0.0% (  0.0/836.2MB) ├──────────────────────────────────────┤[ 1/41] you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
